class xpath_av_by(object):
    AUDI = '//option[@value=6]'
    AUDI_100 = '//option[@value="10"]'
    PRODUCE_YEAR = '//div[@class="dropselect-head js-dropselect-head dropselect-head-year"]'
    PRODUCE_YEAR_FROM = '//select[@name="year_from"]/option[@value="2000"]'
    SEARCH = '//button[@id="submit_presearch"]'
    LISTING_TITLE = '//h3[@class="listing__title"]'
    INPUT_LOGIN = '//input[@id="login"]'
    INPUT_PASSWORD = '//input[@id="password"]'
    USER_BAR = '//li[@class="nav__item nav__item--dropdown nav__item--user"]'
    ERROR_MESSAGE = '//div[@class ="error-message"]'
